imports: 
        - { resource: admin/ }
            
#        - App\Entity\User
    
#        assets:
#            css: # - CSS link
            # - 'bundles/easyadmin/bootstrap-all.css' tout le CSS de Bootstrap
#            js: # - JS link
            # - 'bundles/easyadmin/bootstrap-all.js'
#            favicon: #'/assets/backend/favicon.png' favicon special backend
