easy_admin:
    entities:
        User:
            class: App\Entity\User
            label: 'Paramètres'
            disabled_actions: ['new', 'search']
            form:
                fields: 
                    - { property: 'dailyLimit', label: 'Limite de révisions quotidiennes' }
                    - { property: 'pseudo', label: 'Pseudo' }
                    - { property: 'password', label: 'Password' }
                actions:
                    - { name : 'delete', icon: 'trash', label: 'Supprimer mon compte', css_class: 'btn btn-danger' }
            list:
                fields: [{property: 'pseudo', label: 'Pseudo'}, {property: 'cards', label: 'Nb. cartes'}, {property: 'tags', label: 'Nb. tags'}, {property: 'dailyLimit', label: 'Nb. révisions quotidiennes'}]
                title: "Paramètres"
                actions: 
                    - { name : 'edit', icon: 'pencil', label: false, css_class: 'btn btn-info' }
                    - { name : '-delete' }
            search:
                title: "Le résultat de votre recherche :"
            show:
                title: "Votre flashcard en détail"
            edit:
                title: "Modifier vos paramètres"